// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Deliveries = sequelize.define('deliveries', {
    phone: {
      type: DataTypes.STRING,
    },
    lng: {
      type: DataTypes.DOUBLE,
    },
    lat: {
      type: DataTypes.DOUBLE,
    },
    isDelivered: {
      type: DataTypes.BOOLEAN,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'deliveries',
    underscored: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Deliveries.associate = (models) => {
    Deliveries.hasMany(models.orders, {
      foreignKey: {
        name: 'deliveryIdKey',
        field: 'delivery_id',
      },
      as: 'orders',
    });
  };

  return Deliveries;
};
