// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Transactions = sequelize.define('transactions', {
    beneficiaryIban: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    emitterIban: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    vatAmount: {
      type: DataTypes.INTEGER,
    },
    amount: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    feeAmount: {
      type: DataTypes.INTEGER,
    },
    note: {
      type: DataTypes.STRING,
    },
    emitterBic: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    beneficiaryBic: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    reference: {
      type: DataTypes.STRING,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
    status: {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'transactions',
    underscored: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Transactions.associate = (models) => {
    Transactions.belongsTo(models.companies, {
      foreignKey: {
        name: 'beneficiaryCompanyIdKey',
        field: 'beneficiary_company_id',
      },
      as: 'beneficiaryCompany',
    });
    Transactions.belongsTo(models.companies, {
      foreignKey: {
        name: 'emitterCompanyIdKey',
        field: 'emitter_company_id',
      },
      as: 'emitterCompany',
    });
  };

  return Transactions;
};
